{% set name = "types-urllib3" %}
{% set version = "1.26.25.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-urllib3-{{ version }}.tar.gz
  sha256: 229b7f577c951b8c1b92c1bc2b2fdb0b49847bd2af6d1cc2a2e3dd340f3bda8f

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  description: |
    Typeshed contains external type annotations for the Python standard
    library and Python builtins, as well as third party packages as contributed
    by people external to those projects.
  summary: Typing stubs for urllib3
  license: Apache-2.0
  dev_url: https://github.com/python/typeshed
  doc_url: https://github.com/python/typeshed/blob/main/README.md
  # License need to be packaged from upstream
  license_file: LICENSE
  license_family: APACHE

extra:
  recipe-maintainers:
    - thewchan