{% set name = "types-urllib3" %}
{% set version = "1.26.25.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-urllib3-{{ version }}.tar.gz
  sha256: c44881cde9fc8256d05ad6b21f50c4681eb20092552351570ab0a8a0653286d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for urllib3
  license: Apache-2.0
  # License need to be packaged from upstream
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
