{% set name = "types-urllib3" %}
{% set version = "1.26.25.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-urllib3-{{ version }}.tar.gz
  sha256: 3300538c9dc11dad32eae4827ac313f5d986b8b21494801f1bf97a1ac6c03ae5

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  description: |
    Typeshed contains external type annotations for the Python standard
    library and Python builtins, as well as third party packages as contributed
    by people external to those projects.
  summary: Typing stubs for urllib3
  license: Apache-2.0
  dev_url: https://github.com/python/typeshed
  doc_url: https://github.com/python/typeshed/blob/main/README.md
  # License need to be packaged from upstream
  license_file: LICENSE
  license_family: APACHE

extra:
  recipe-maintainers:
    - thewchan
